#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

version: '3'

networks:
  fabricstar:
    external:
      name: fabricstar

services:

    kafka0:        
        image: ${KAFKAIMAGE}
        environment:
        - KAFKA_MESSAGE_MAX_BYTES=1073741824  # 1024 * 1024 B
        - KAFKA_REPLICA_FETCH_MAX_BYTES=1073741824  # 1024 * 1024 B
        - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
        - KAFKA_BROKER_ID=0
        - KAFKA_MIN_INSYNC_REPLICAS=2
        - KAFKA_DEFAULT_REPLICATION_FACTOR=3
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
        ports:
        - 9092:9092
        networks:
          - fabricstar
        volumes:
        - ../../../KafkaKeyPair:/etc/KafkaKeyPair
        deploy:
          replicas: 1
          restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3
          placement:
              constraints: [node.hostname ==  peer0]                   

    kafka1:        
        image: ${KAFKAIMAGE}
        environment:
        - KAFKA_MESSAGE_MAX_BYTES=1073741824  # 1024 * 1024 B
        - KAFKA_REPLICA_FETCH_MAX_BYTES=1073741824  # 1024 * 1024 B
        - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
        - KAFKA_BROKER_ID=1
        - KAFKA_MIN_INSYNC_REPLICAS=2
        - KAFKA_DEFAULT_REPLICATION_FACTOR=3
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
        ports:
        - 9093:9092
        networks:
          - fabricstar
        volumes:
        - ../../../KafkaKeyPair:/etc/KafkaKeyPair
        deploy:
          replicas: 1
          restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3
          placement:
              constraints: [node.hostname ==  peer1]                                      

    kafka2:        
        image: ${KAFKAIMAGE}
        environment:
        - KAFKA_MESSAGE_MAX_BYTES=1073741824  # 1024 * 1024 B
        - KAFKA_REPLICA_FETCH_MAX_BYTES=1073741824  # 1024 * 1024 B
        - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
        - KAFKA_BROKER_ID=2
        - KAFKA_MIN_INSYNC_REPLICAS=2
        - KAFKA_DEFAULT_REPLICATION_FACTOR=3
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
        ports:
        - 9094:9092
        networks:
          - fabricstar
        volumes:
        - ../../../KafkaKeyPair:/etc/KafkaKeyPair
        deploy:
          replicas: 1
          restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3
          placement:
              constraints: [node.hostname ==  caliperworker1]                      

    kafka3:        
        image: ${KAFKAIMAGE}
        environment:
        - KAFKA_MESSAGE_MAX_BYTES=1073741824  # 1024 * 1024 B
        - KAFKA_REPLICA_FETCH_MAX_BYTES=1073741824  # 1024 * 1024 B
        - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
        - KAFKA_BROKER_ID=3
        - KAFKA_MIN_INSYNC_REPLICAS=2
        - KAFKA_DEFAULT_REPLICATION_FACTOR=3
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
        ports:
        - 9095:9092
        networks:
          - fabricstar
        volumes:
        - ../../../KafkaKeyPair:/etc/KafkaKeyPair
        deploy:
          replicas: 1
          restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3
          placement:
              constraints: [node.hostname ==  caliperworker3]                               