version: '3'

networks:
  fabricstar:
    external:
      name: fabricstar

services:
    caliperManager:
        image: fabric_star/caliper
        command: launch manager
        environment:
        - CALIPER_BENCHCONFIG=${BENCHMARK}
        - CALIPER_NETWORKCONFIG=network/config/fabric-api-node.yaml
        - CALIPER_FABRIC_SLEEPAFTER_CREATECHANNEL=10000
        - CALIPER_FABRIC_SLEEPAFTER_JOINCHANNEL=10000
        - CALIPER_FABRIC_SLEEPAFTER_INSTANTIATECONTRACT=10000
        - CALIPER_WORKER_COMMUNICATION_METHOD=mqtt
        - CALIPER_WORKER_COMMUNICATION_ADDRESS=mqtt://mosquitto:1883
        - CALIPER_WORKER_REMOTE=true
        volumes:
        - ~/caliper-benchmarks:/hyperledger/caliper/workspace
        networks:
          - fabricstar
        deploy:
          replicas: 1
          restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3
          placement:
              constraints: [node.hostname == orderer2]                                                                                         

    caliperWorker1:
        image: fabric_star/caliper
        command: launch worker
        environment:
        - CALIPER_BENCHCONFIG=${BENCHMARK}
        - CALIPER_NETWORKCONFIG=network/config/fabric-api-node.yaml
        - CALIPER_FABRIC_SLEEPAFTER_CREATECHANNEL=10000
        - CALIPER_FABRIC_SLEEPAFTER_JOINCHANNEL=10000
        - CALIPER_FABRIC_SLEEPAFTER_INSTANTIATECONTRACT=10000
        - CALIPER_WORKER_COMMUNICATION_METHOD=mqtt
        - CALIPER_WORKER_COMMUNICATION_ADDRESS=mqtt://mosquitto:1883
        - CALIPER_WORKER_REMOTE=true
        volumes:
        - ~/caliper-benchmarks:/hyperledger/caliper/workspace
        networks:
          - fabricstar
        deploy:
          replicas: 8
          restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3                                                                                               
          placement:
              constraints: [node.hostname == peer2]     
              
    caliperWorker2:
        image: fabric_star/caliper
        command: launch worker
        environment:
        - CALIPER_BENCHCONFIG=${BENCHMARK}
        - CALIPER_NETWORKCONFIG=network/config/fabric-api-node.yaml
        - CALIPER_FABRIC_SLEEPAFTER_CREATECHANNEL=10000
        - CALIPER_FABRIC_SLEEPAFTER_JOINCHANNEL=10000
        - CALIPER_FABRIC_SLEEPAFTER_INSTANTIATECONTRACT=10000
        - CALIPER_WORKER_COMMUNICATION_METHOD=mqtt
        - CALIPER_WORKER_COMMUNICATION_ADDRESS=mqtt://mosquitto:1883
        - CALIPER_WORKER_REMOTE=true
        volumes:
        - ~/caliper-benchmarks:/hyperledger/caliper/workspace
        networks:
          - fabricstar
        deploy:
          replicas: 8
          restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3                                                                                               
          placement:
              constraints: [node.hostname == peer3]    

    caliperWorker3:
        image: fabric_star/caliper
        command: launch worker
        environment:
        - CALIPER_BENCHCONFIG=${BENCHMARK}
        - CALIPER_NETWORKCONFIG=network/config/fabric-api-node.yaml
        - CALIPER_FABRIC_SLEEPAFTER_CREATECHANNEL=10000
        - CALIPER_FABRIC_SLEEPAFTER_JOINCHANNEL=10000
        - CALIPER_FABRIC_SLEEPAFTER_INSTANTIATECONTRACT=10000
        - CALIPER_WORKER_COMMUNICATION_METHOD=mqtt
        - CALIPER_WORKER_COMMUNICATION_ADDRESS=mqtt://mosquitto:1883
        - CALIPER_WORKER_REMOTE=true
        volumes:
        - ~/caliper-benchmarks:/hyperledger/caliper/workspace
        networks:
          - fabricstar
        deploy:
          replicas: 4
          restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3                                                                                               
          placement:
              constraints: [node.hostname == peer4]                          

                                                                                         
