#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

version: '3'

networks:
  fabricstar:
    external:
      name: fabricstar

services: 
    zookeeper0:
        image: hyperledger/fabric-zookeeper
        environment:
        - ZOO_MY_ID=1
        - ZOO_SERVERS=server.1=0.0.0.0:2888:3888 
        # - ZOO_SERVERS=server.1=0.0.0.0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
        ports:
        - 2181:2181
        networks:
          - fabricstar
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3  
          placement:
              constraints: [node.hostname ==  peer3]        

    # zookeeper1:     
    #     image: hyperledger/fabric-zookeeper
    #     environment:
    #     - ZOO_MY_ID=2
    #     - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zookeeper2:2888:3888
    #     ports:
    #     - 2182:2181
    #     networks:
    #       - fabricstar
    #     deploy:
    #       replicas: 1
    #       restart_policy:
    #         condition: on-failure
    #         delay: 5s
    #         max_attempts: 3  
    #       placement:
    #           constraints: [node.hostname ==  kafka1]               

    # zookeeper2:     
    #     image: hyperledger/fabric-zookeeper
    #     environment:
    #     - ZOO_MY_ID=3
    #     - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=0.0.0.0:2888:3888
    #     ports:
    #     - 2183:2181
    #     networks:
    #       - fabricstar
    #     deploy:
    #       replicas: 1
    #       restart_policy:
    #         condition: on-failure
    #         delay: 5s
    #         max_attempts: 3  
    #       placement:
    #           constraints: [node.hostname ==  kafka2]              
