version: '3'

networks:
  fabricstar:
    external:
      name: fabricstar

services:
    caliperManager:
        image: hyperledger/caliper:0.3.2
        command: launch master
        environment:
        - CALIPER_BIND_SUT=fabric:latest
        - CALIPER_BENCHCONFIG=${BENCHMARK}
        - CALIPER_NETWORKCONFIG=network/config/fabric-api-node.yaml
        - CALIPER_FABRIC_SLEEPAFTER_CREATECHANNEL=10000
        - CALIPER_FABRIC_SLEEPAFTER_JOINCHANNEL=10000
        - CALIPER_FABRIC_SLEEPAFTER_INSTANTIATECONTRACT=10000
        - CALIPER_WORKER_COMMUNICATION_METHOD=mqtt
        - CALIPER_WORKER_COMMUNICATION_ADDRESS=mqtt://mosquitto:1883
        - CALIPER_WORDER_REMOTE=true
        volumes:
        - ~/caliper-benchmarks:/hyperledger/caliper/workspace
        networks:
          - fabricstar
        deploy:
          replicas: 1
          restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3
          placement:
              constraints: [node.hostname == calipermanager]                                                                                       

    mosquitto:
        image: eclipse-mosquitto
        restart: always
        ports:
        - "1883:1883"
        - "9001:9001"
        volumes:
        - ../../config/mosquitto.conf:/mosquitto/config/mosquitto.conf   
        networks:
          - fabricstar
        deploy:
          replicas: 1
          restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3
          placement:
              constraints: [node.hostname == calipermanager]             
