global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: 'prometheus-peer'

    # Retain labels, as within PushGateway use
    honor_labels: true

    static_configs:
    - targets: ['prometheus:9090', 'pushGateway:9091', 'peer0.org1.example.com:9443', 'peer0.org2.example.com:9443', 'peer0.org3.example.com:9443', 'peer0.org4.example.com:9443', 'peer0.org5.example.com:9443']

  - job_name: 'prometheus-orderer'

    # Retain labels, as within PushGateway use
    honor_labels: true

    static_configs:
    - targets: ['prometheus:9090', 'pushGateway:9091',orderer0.example.com:8443, orderer1.example.com:8443, orderer2.example.com:8443]

  # - job_name: cadvisor
  #   scrape_interval: 5s
  #   static_configs:
  #   - targets: ['cadvisor:8080']

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080