global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: 'prometheus-peer'

    # Retain labels, as within PushGateway use
    honor_labels: true

    static_configs:
    - targets: ['prometheus:9090', 'pushGateway:9091', 'peer0.org1.example.com:9443', 'peer0.org2.example.com:9443', 'peer0.org3.example.com:9443', 'peer0.org4.example.com:9443', 'peer0.org5.example.com:9443']

  - job_name: 'prometheus-orderer'

    # Retain labels, as within PushGateway use
    honor_labels: true

    static_configs:
    - targets: ['prometheus:9090', 'pushGateway:9091',orderer0.example.com:8443, orderer1.example.com:8443, orderer2.example.com:8443]

  - job_name: 'prometheus-kafka'

    # Retain labels, as within PushGateway use
    honor_labels: true

    static_configs:    
    - targets: ['kafka0:9092', 'kafka1:9092', 'kafka2:9092', 'kafka3:9092']    

  - job_name: 'cadvisor'
    honor_labels: true
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'nodeexporter'
    honor_labels: true  
    dns_sd_configs:
    - names:
      - 'tasks.nodeexporter'
      type: 'A'
      port: 9100

  - job_name: 'dockerswarm'
    honor_labels: true
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      # Only keep containers that should be running.
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep
      # Only keep containers that have a `prometheus-job` label.
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        regex: .+
        action: keep
      # Use the prometheus-job Swarm label as Prometheus job label.
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        target_label: job      