#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Fabric
version: "1.0"
mutual-tls: false

caliper:
    blockchain: fabric

info:
    Version: 1.4
    Size: 5 Orgs with 1 Peer
    Orderer: Kafka
    Distribution: Single Host
    StateDB: GoLevelDB

clients:
    client0.org1.example.com:
        client:
            organization: Org1
            credentialStore:
                path: /tmp/hfc-kvs/org1
                cryptoStore:
                    path: /tmp/hfc-cvs/org1
            clientPrivateKey:
                path: network/resources/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/key.pem
            clientSignedCert:
                path: network/resources/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem

    client0.org2.example.com:
        client:
            organization: Org2
            credentialStore:
                path: /tmp/hfc-kvs/org2
                cryptoStore:
                    path: /tmp/hfc-cvs/org2
            clientPrivateKey:
                path: network/resources/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/key.pem
            clientSignedCert:
                path: network/resources/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/User1@org2.example.com-cert.pem              

    client0.org3.example.com:
        client:
            organization: Org3
            credentialStore:
                path: /tmp/hfc-kvs/org3
                cryptoStore:
                    path: /tmp/hfc-cvs/org3
            clientPrivateKey:
                path: network/resources/crypto-config/peerOrganizations/org3.example.com/users/User1@org3.example.com/msp/keystore/key.pem
            clientSignedCert:
                path: network/resources/crypto-config/peerOrganizations/org3.example.com/users/User1@org3.example.com/msp/signcerts/User1@org3.example.com-cert.pem   

    client0.org4.example.com:
        client:
            organization: Org4
            credentialStore:
                path: /tmp/hfc-kvs/org4
                cryptoStore:
                    path: /tmp/hfc-cvs/org4
            clientPrivateKey:
                path: network/resources/crypto-config/peerOrganizations/org4.example.com/users/User1@org4.example.com/msp/keystore/key.pem
            clientSignedCert:
                path: network/resources/crypto-config/peerOrganizations/org4.example.com/users/User1@org4.example.com/msp/signcerts/User1@org4.example.com-cert.pem 

    # client0.org5.example.com:
    #     client:
    #         organization: Org5
    #         credentialStore:
    #             path: /tmp/hfc-kvs/org5
    #             cryptoStore:
    #                 path: /tmp/hfc-cvs/org5
    #         clientPrivateKey:
    #             path: network/resources/crypto-config/peerOrganizations/org5.example.com/users/User1@org5.example.com/msp/keystore/key.pem
    #         clientSignedCert:
    #             path: network/resources/crypto-config/peerOrganizations/org5.example.com/users/User1@org5.example.com/msp/signcerts/User1@org5.example.com-cert.pem                                            

channels:
    mychannel:
        created: false
        definition:
            capabilities: []
            consortium: "SampleConsortium"
            msps: ["Org1MSP", "Org2MSP", "Org3MSP", "Org4MSP"]
            version: 0
        orderers:
            - orderer0.example.com
            - orderer1.example.com
            - orderer2.example.com
        peers:
            peer0.org1.example.com:
                eventSource: true
            peer1.org1.example.com:
                eventSource: true
            peer0.org2.example.com:
                eventSource: true
            peer1.org2.example.com:
                eventSource: true                
            peer0.org3.example.com:
                eventSource: true
            peer1.org3.example.com:
                eventSource: true                
            peer0.org4.example.com:
                eventSource: true
            peer1.org4.example.com:
                eventSource: true                
            # peer0.org5.example.com:
            #     eventSource: true   
            # peer1.org5.example.com:
            #     eventSource: true                                                

        contracts:
            - id: fixed-asset
              version: v0
              language: node
              path: src/fabric/api/fixed-asset/node
              metadataPath: src/fabric/api/fixed-asset/metadata  
            #   endorsement-policy: { "identities": [{ "role": { "name": "member", "mspId": "Org1MSP" }},{ "role": { "name": "member", "mspId": "Org2MSP" }},{ "role": { "name": "member", "mspId": "Org3MSP" }},{ "role": { "name": "member", "mspId": "Org4MSP" }},{ "role": { "name": "member", "mspId": "Org5MSP" }},{ "role": { "name": "admin", "mspId": "Org1MSP" }},{ "role": { "name": "admin", "mspId": "Org2MSP" }},{ "role": { "name": "admin", "mspId": "Org3MSP" }},{ "role": { "name": "admin", "mspId": "Org4MSP" }},{ "role": { "name": "admin", "mspId": "Org5MSP" }}],"policy": {"1-of": [{ "signed-by": 0}, { "signed-by": 1 }, { "signed-by": 2 }, { "signed-by": 3}, { "signed-by": 4}, { "signed-by": 5}, { "signed-by": 6}, { "signed-by": 7}, { "signed-by": 8}, { "signed-by": 9}, { "signed-by": 10}]}}                 
              endorsement-policy: { "identities": [{ "role": { "name": "member", "mspId": "Org1MSP" }},{ "role": { "name": "member", "mspId": "Org2MSP" }},{ "role": { "name": "member", "mspId": "Org3MSP" }},{ "role": { "name": "member", "mspId": "Org4MSP" }}], "policy": {"1-of": [{ "signed-by": 0}, { "signed-by": 1 }, { "signed-by": 2 }, { "signed-by": 3 }]}}

organizations:
    Org1:
        mspid: Org1MSP
        peers:
            - peer0.org1.example.com
            - peer1.org1.example.com
        certificateAuthorities:
            - ca.org1.example.com
        adminPrivateKey:
            path: network/resources/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/key.pem
        signedCert:
            path: network/resources/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem

    Org2:
        mspid: Org2MSP
        peers:
            - peer0.org2.example.com
            - peer1.org2.example.com
        certificateAuthorities:
            - ca.org2.example.com
        adminPrivateKey:
            path: network/resources/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/key.pem
        signedCert:
            path: network/resources/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem

    Org3:
        mspid: Org3MSP
        peers:
            - peer0.org3.example.com
            - peer1.org3.example.com
        certificateAuthorities:
            - ca.org3.example.com
        adminPrivateKey:
            path: network/resources/crypto-config/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp/keystore/key.pem
        signedCert:
            path: network/resources/crypto-config/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp/signcerts/Admin@org3.example.com-cert.pem   

    Org4:
        mspid: Org4MSP
        peers:
            - peer0.org4.example.com
            - peer1.org4.example.com
        certificateAuthorities:
            - ca.org4.example.com
        adminPrivateKey:
            path: network/resources/crypto-config/peerOrganizations/org4.example.com/users/Admin@org4.example.com/msp/keystore/key.pem
        signedCert:
            path: network/resources/crypto-config/peerOrganizations/org4.example.com/users/Admin@org4.example.com/msp/signcerts/Admin@org4.example.com-cert.pem    

    # Org5:
    #     mspid: Org5MSP
    #     peers:
    #         - peer0.org5.example.com
    #         - peer1.org5.example.com
    #     certificateAuthorities:
    #         - ca.org5.example.com
    #     adminPrivateKey:
    #         path: network/resources/crypto-config/peerOrganizations/org5.example.com/users/Admin@org5.example.com/msp/keystore/key.pem
    #     signedCert:
    #         path: network/resources/crypto-config/peerOrganizations/org5.example.com/users/Admin@org5.example.com/msp/signcerts/Admin@org5.example.com-cert.pem                        

orderers:
    orderer0.example.com:
        url: grpc://orderer0.example.com:7050
        grpcOptions:
            ssl-target-name-override: orderer0.example.com         

    orderer1.example.com:
        url: grpc://orderer1.example.com:7050
        grpcOptions:
            ssl-target-name-override: orderer1.example.com     

    orderer2.example.com:
        url: grpc://orderer2.example.com:7050
        grpcOptions:
            ssl-target-name-override: orderer2.example.com                         

peers:
    peer0.org1.example.com:
        url: grpc://peer0.org1.example.com:7051
        grpcOptions:
            ssl-target-name-override: peer0.org1.example.com
            grpc.keepalive_time_ms: 600000

    peer1.org1.example.com:
        url: grpc://peer1.org1.example.com:7051
        grpcOptions:
            ssl-target-name-override: peer1.org1.example.com
            grpc.keepalive_time_ms: 600000

    peer0.org2.example.com:
        url: grpc://peer0.org2.example.com:7051
        grpcOptions:
            ssl-target-name-override: peer0.org2.example.com
            grpc.keepalive_time_ms: 600000

    peer1.org2.example.com:
        url: grpc://peer1.org2.example.com:7051
        grpcOptions:
            ssl-target-name-override: peer1.org2.example.com
            grpc.keepalive_time_ms: 600000            

    peer0.org3.example.com:
        url: grpc://peer0.org3.example.com:7051
        grpcOptions:
            ssl-target-name-override: peer0.org3.example.com
            grpc.keepalive_time_ms: 600000     

    peer1.org3.example.com:
        url: grpc://peer1.org3.example.com:7051
        grpcOptions:
            ssl-target-name-override: peer1.org3.example.com
            grpc.keepalive_time_ms: 600000                  

    peer0.org4.example.com:
        url: grpc://peer0.org4.example.com:7051
        grpcOptions:
            ssl-target-name-override: peer0.org4.example.com
            grpc.keepalive_time_ms: 600000     

    peer1.org4.example.com:
        url: grpc://peer1.org4.example.com:7051
        grpcOptions:
            ssl-target-name-override: peer1.org4.example.com
            grpc.keepalive_time_ms: 600000               

    # peer0.org5.example.com:
    #     url: grpc://peer0.org5.example.com:7051
    #     grpcOptions:
    #         ssl-target-name-override: peer0.org5.example.com
    #         grpc.keepalive_time_ms: 600000      

    # peer1.org5.example.com:
    #     url: grpc://peer1.org5.example.com:7051
    #     grpcOptions:
    #         ssl-target-name-override: peer1.org5.example.com
    #         grpc.keepalive_time_ms: 600000                                 

certificateAuthorities:
    ca.org1.example.com:
        url: http://ca.org1.example.com:7054
        httpOptions:
            verify: false
        registrar:
            - enrollId: admin
              enrollSecret: adminpw

    ca.org2.example.com:
        url: http://ca.org2.example.com:7054
        httpOptions:
            verify: false
        registrar:
            - enrollId: admin
              enrollSecret: adminpw

    ca.org3.example.com:
        url: http://ca.org3.example.com:7054
        httpOptions:
            verify: false
        registrar:
            - enrollId: admin
              enrollSecret: adminpw

    ca.org4.example.com:
        url: http://ca.org4.example.com:7054
        httpOptions:
            verify: false
        registrar:
            - enrollId: admin
              enrollSecret: adminpw

    # ca.org5.example.com:
    #     url: http://ca.org5.example.com:7054
    #     httpOptions:
    #         verify: false
    #     registrar:
    #         - enrollId: admin
    #           enrollSecret: adminpw                                          
