version: '3'

volumes:
    prometheus_data: {}
    grafana_storage: {}

networks:
  fabricstar:
    external:
      name: fabricstar

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus-fabric.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=https://0.0.0.0/prometheus'
      - '--web.route-prefix=/'
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3        
      placement:
          constraints: [node.hostname == caliperworker2]       
    networks:
      fabricstar:
        aliases:
          - prometheus      

  pushGateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3        
      placement:
          constraints: [node.hostname == caliperworker2]       
    networks:
      fabricstar:
        aliases:
          - pushGateway  

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3        
      placement:
          constraints: [node.hostname == caliperworker2] 
    networks:
      fabricstar:
        aliases:
          - grafana      

  cadvisor:
    image: google/cadvisor:v0.27.4
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      # - /cgroup:/cgroup:ro
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3        
      mode: global
    networks:
      - fabricstar
      
  nodeexporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3        
      mode: global
    ports:
      - 9100:9100
    networks:
      - fabricstar       
